const config = {
  IOS_API_KEY: "REPLACE_WITH_YOU_API_KEY",
  ANDROID_API_KEY: "REPLACE_WITH_YOU_API_KEY",
  MAP_API_KEY: "REPLACE_WITH_YOU_API_KEY",
  PLACES_API_KEY: "REPLACE_WITH_YOU_API_KEY",
  DIRECTION_API_KEY: "REPLACE_WITH_YOU_API_KEY",
  GEOCODE_API_KEY: "REPLACE_WITH_YOU_API_KEY",
  API_KEY_FOR_PLACES: "REPLACE_WITH_YOU_API_KEY",
};

export { config };
