const config = {
  IOS_API_KEY: "REPLACE_WITH_YOU_API_KEY",
  ANDROID_API_KEY: "REPLACE_WITH_YOU_API_KEY",
  MAP_API_KEY: "AIzaSyC4pPKjHm_73tLXB5Huj4SdL_4AJsVpueg",
  PLACES_API_KEY: "AIzaSyDW4Z9Isw84xMrAtdw8IhNBzGQmNlIp0Pk",
  DIRECTION_API_KEY: "AIzaSyBL7lGdtl_KPP_Kp8V34ULIwOQKiF3Z2Ao",
  GEOCODE_API_KEY: "AIzaSyAnYxUamBQGo7fYkI68W3eehWI_znSVxoU",
  API_KEY_FOR_PLACES: "AIzaSyDhARuvPnY3-bCJvu7FavCdichpag3-LDY",
};

export { config };
